version: "3.9"

services:
  k8s-master:
    image: rancher/k3s:v1.30.4-k3s1
    privileged: true
    environment:
      K3S_KUBECONFIG_OUTPUT: /output/kubeconfig.yaml
      K3S_KUBECONFIG_MODE: "644"
    command:
      - server
      - --disable=traefik
    volumes:
      - ./k3s:/output
    ports:
      - "6443:6443"