version: "3.9"

services:
  frontend:
    build: ./frontend
    environment:
      API_URL: http://backend:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - "3000:3000"